name: Happo CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Print GH vars
        run: |
          echo ${{ github.ref }}
          echo ${{ github.base_ref }}
      - uses: dorny/paths-filter@v2
        id: filterfix-
        with:
          filters: |
            frontend:
              - 'src/**'
              - '.storybook/**'
              - '.happo.js'
              - 'yarn.lock'

  happo:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' || github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.3'

      - name: Install dependencies
        run: yarn install

      - name: Start Happo run
        run: yarn happo-ci-github-actions
        env:
          HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
          HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
